import { LabPhoto } from "@/components/lab-photo";
import { LabPowerEstimate } from "@/components/lab-power-estimate";
import { FounderLinks } from "@/components/v2/shared";
import inventory from "@/content/lab-inventory.json";
import { hardware } from "@/content/v2/hardware";
import { siteConfig } from "@/lib/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("The Lab", "Request free Lab compute for open source projects and open research. See the hardware, application steps, and current limits.", "/lab");

export default function LabPage() {
  const acquisitions = inventory.items.filter(item => "recentAcquisition" in item);
  const snapshot = new Date(`${inventory.snapshot}T12:00:00Z`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" });
  return <>
    <header className="v2-hero-surface"><div className="v2-wrap v2-lab-hero"><div><p className="v2-kicker">The Hackers in the Loop Lab</p><h1>Free compute for open work.</h1><p className="v2-lede">This Lab exists to help people build open source projects and do open research. Tell us what you want to try. We review requests and share hardware when capacity is available.</p><div className="v2-actions"><a className="v2-button v2-button--primary" href={siteConfig.labRequestUrl} target="_blank" rel="noreferrer">Request free compute ↗</a><a className="v2-link" href="#access">How it works ↓</a></div></div><LabPhoto name="cluster-complete" priority alt="The assembled Hackers in the Loop mini rack with three DGX Sparks, network cabling, storage, and an external GPU bench." /></div></header>

    <section className="v2-access" id="access" aria-labelledby="access-title"><div className="v2-wrap v2-section v2-access-inner"><div><p className="v2-kicker">Open source and open research</p><h2 id="access-title">Your project can use the Lab.</h2></div><div><p>Compute grants are free. Tell us what you want to build or study, what hardware and time you need, and how you plan to share the work publicly.</p><p>Requests are reviewed against available capacity. Applying does not reserve hardware or create immediate access.</p><div className="v2-actions"><a className="v2-button v2-button--primary" href={siteConfig.labRequestUrl} target="_blank" rel="noreferrer">Apply for free compute ↗</a><a className="v2-link" href="/community#connect">Join the community →</a></div></div></div></section>

    <nav className="v2-wrap v2-jump" aria-label="Lab sections"><a href="#hardware">Hardware</a><a href="/projects">Projects</a><a href="#support">Support the Lab</a><a href="#costs">Costs & power</a><a href="#journey">Build journey</a></nav>

    <section className="v2-wrap v2-section" id="hardware" aria-labelledby="hardware-title"><div className="v2-section-heading"><p className="v2-kicker">Inventory / {snapshot}</p><h2 id="hardware-title">What’s in the Lab.</h2></div><p className="v2-note">Equipment and experimental configurations from the build notes and subsequent acquisitions. The inventory does not indicate remote availability or member allocations.</p><div className="v2-hardware">{hardware.map(([label,title,copy])=><article key={label}><p className="v2-kicker">{label}</p><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="v2-actions"><a className="v2-link" href="/lab/hack-lab-inventory.xlsx" download>Download inventory, costs & power (Excel) ↓</a><a className="v2-link" href="/projects">See experiments & their hardware →</a></div></section>

    <section className="v2-wrap v2-section v2-acquisitions" id="recently-acquired" aria-labelledby="acquisitions-title"><div className="v2-section-heading"><p className="v2-kicker">New in the Lab</p><h2 id="acquisitions-title">Recently acquired.</h2></div><p className="v2-note">These cards are in the inventory. Their installation and availability for grants have not been confirmed. Prices use comparable current retail listings; card power figures are design references, not measured Lab draw.</p><div className="v2-acquisition-list">{acquisitions.map(item => <article key={item.id} className="v2-acquisition"><div><p className="v2-kicker">{item.recentAcquisition?.status} / Quantity {item.quantity}</p><h3>{item.name}</h3></div><div><p>{item.recentAcquisition?.description}</p><p className="v2-note">Cost reference: ${item.unitCostUSD.toLocaleString("en-US", {minimumFractionDigits: 2, maximumFractionDigits: 2})} each. {item.costBasis}. <a href={item.sourceUrls[0].url} target="_blank" rel="noreferrer">Price source ↗</a></p><p className="v2-note">Power reference: {item.powerReference?.summary}. <a href={item.powerReference?.sourceUrls[0].url} target="_blank" rel="noreferrer">Power source ↗</a></p></div></article>)}</div></section>

    <section className="v2-dark" id="support" aria-labelledby="support-title"><div className="v2-wrap v2-section"><p className="v2-kicker">Support the Lab</p><h2 id="support-title">Have hardware or hosting space to offer?</h2><p className="v2-lede">Hardware and hosting support can make more room for community projects. Tell us what you can offer and any constraints.</p><div className="v2-support-options"><article><h3>Hosting.</h3><p>The build uses a 12U, 10-inch mini rack with external benches. Share your location, available space, power and network capacity, and any operating or access constraints.</p><a className="v2-link" href="#costs">See the power estimates ↓</a></article><article><h3>Hardware that fits.</h3><p>Tell us the model, condition, and location of equipment you can offer. We can discuss it against the existing inventory and what the Lab needs.</p></article></div><div className="v2-support-contact"><div><h3>Start with a conversation.</h3><p className="v2-note" style={{marginTop:'.75rem'}}>Tell us what you can offer and any constraints. Equipment, delivery, hosting, and operating arrangements can be discussed before anything changes hands.</p></div><FounderLinks /></div></div></section>

    <section className="v2-wrap v2-section v2-costs" id="costs" aria-labelledby="costs-title"><div className="v2-section-heading"><p className="v2-kicker">Stewardship / Planning estimates</p><h2 id="costs-title">What it takes to run.</h2></div><div className="v2-cost-layout"><div><p className="v2-kicker">Equipment cost estimate</p><p className="v2-cost-total">${inventory.controls.totalCostUSD.toLocaleString()}</p><p className="v2-note">Dated replacement references, comparable-item allowances, and two owner-reported prices. All {inventory.items.length} inventory lines have a cost reference. This estimate is not the amount paid or a confirmed replacement quote. Exact board models for the new GPUs, the NanoKVM, and soldering setup are still unknown; CoreS3 is provisionally treated as an additional unit.</p><dl className="lab-cost-breakdown"><div><dt>Compute hardware & add-ons</dt><dd>${inventory.controls.computeCostUSD.toLocaleString()}</dd></div><div><dt>Rack, network, control & power</dt><dd>${inventory.controls.sharedCostUSD.toLocaleString()}</dd></div></dl><a className="v2-link" href="/lab/hack-lab-inventory.xlsx" download>Itemized inventory, costs & power (Excel) ↓</a><h3>Estimated wall power</h3><div className="lab-table-wrap"><table className="lab-power-table"><caption>Watts by workload scenario</caption><thead><tr><th scope="col">Setup</th><th scope="col">Idle</th><th scope="col">Working</th><th scope="col">Heavy</th></tr></thead><tbody><tr><th scope="row">Core cluster</th><td>229.8 W</td><td>406.5 W</td><td>907 W</td></tr><tr><th scope="row">Whole lab</th><td>339.3 W</td><td>693 W</td><td>1,413 W</td></tr></tbody></table></div><p className="v2-note">Planning estimates, not meter readings. The documented GPU dock scenario uses one V100; the P4 and four newly acquired cards are not added to it. Whole lab also includes the FPGA and small-device benches and a projected populated Agent Blade. The 2070 VA UPS is not modeled because its installation and protected loads are unconfirmed. Its output rating does not describe wall consumption.</p><p className="v2-note">The inventory workbook includes each item’s cost, its power group, and the assumptions behind these estimates. Shared components and spare cards are not counted twice.</p></div><LabPowerEstimate /></div></section>

    <section className="v2-connection" id="journey" aria-labelledby="journey-title"><div className="v2-wrap v2-section"><div className="v2-section-heading"><p className="v2-kicker">September 6–8, 2026 / The build journey</p><h2 id="journey-title">Built together.<br />Learned along the way.</h2></div><div className="v2-split"><LabPhoto name="building-together" alt="Shannon and his daughter beside the mini cluster they built together." caption="Shannon and his daughter with the assembled rack." /><div className="v2-prose"><p>This mini cluster was a project Shannon built with his daughter.</p><p>The first evening meant laying out parts, assembling the rack, and figuring out how everything would fit. His daughter picked the colorful zip ties for the exhaust fan and suggested putting a mini PC on the back to make room.</p><p>After coffee and donuts, they returned to network cabling, cooling, and conversations about AC, DC, and why current matters. By September 8, the first two Sparks and a mini PC were online, brought up one system at a time using a Mac and HDMI capture as the console.</p><div className="v2-actions"><a className="v2-button" href={siteConfig.buildThreadUrl} target="_blank" rel="noreferrer">Follow the build thread on X ↗</a></div></div></div><div className="v2-journey-gallery"><LabPhoto name="parts-on-the-bench" alt="Cluster parts, tools, and hardware laid out before assembly." caption="September 6: laying out the parts." /><LabPhoto name="rack-assembly" alt="The empty TecMOJO rack frame being assembled on the floor." caption="September 6: assembling the rack." /><LabPhoto name="sparks-in-the-rack" alt="Shannon’s daughter beside the rack with three DGX Sparks installed." caption="September 7: three Sparks mounted." /><LabPhoto name="gpu-test-bench" alt="The external GPU bench with a graphics card, power supply, cables, and cooling fans." caption="The swappable GPU bench." /></div></div></section>
  </>;
}
