import { LabPhoto } from "@/components/lab-photo";
import { LabPowerEstimate } from "@/components/lab-power-estimate";
import { FounderLinks, LabStatus } from "@/components/v2/shared";
import { hardware } from "@/content/v2/hardware";
import { siteConfig } from "@/lib/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("The Lab", "Explore the HITL Lab hardware, request compute time for open projects, or discuss supporting the Lab with hardware and hosting.", "/v2/lab");

export default function LabPage() {
  return <>
    <header className="v2-wrap v2-lab-hero"><div><p className="v2-kicker">The HITL Lab</p><h1>Real hardware.<br />Room to experiment.</h1><p className="v2-lede">A mini cluster and test benches built by Shannon Duncan for open source work, with the aim of sharing spare capacity so more people can learn, research, and build.</p><LabStatus /><div className="v2-actions"><a className="v2-button v2-button--primary" href="#access">Request free compute time ↓</a><a className="v2-link" href="#support">Support the Lab</a></div><p className="v2-note">For open research and projects, with public progress and results. Review the application expectations below.</p></div><LabPhoto name="cluster-complete" priority alt="The assembled HITL mini rack with three DGX Sparks, network cabling, storage, and an external GPU bench." caption="The mini cluster and GPU bench during the build." /></header>
    <nav className="v2-wrap v2-jump" aria-label="Lab sections"><a href="#hardware">Hardware</a><a href="/v2/projects">Projects</a><a href="#access">Compute requests</a><a href="#support">Support</a><a href="#costs">Costs & power</a><a href="#journey">Build journey</a></nav>

    <section className="v2-wrap v2-section" id="hardware" aria-labelledby="hardware-title"><div className="v2-section-heading"><p className="v2-kicker">Inventory / September 12, 2026</p><h2 id="hardware-title">What’s in the Lab.</h2></div><p className="v2-note">Equipment and experimental configurations from the build notes. The inventory does not indicate remote availability or member allocations.</p><div className="v2-hardware">{hardware.map(([label,title,copy])=><article key={label}><p className="v2-kicker">{label}</p><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="v2-actions"><a className="v2-link" href="/lab/machines.txt" download>Download the inventory ↓</a><a className="v2-link" href="/v2/projects">See experiments & their hardware →</a></div></section>

    <section className="v2-access" id="access" aria-labelledby="access-title"><div className="v2-wrap v2-section"><div className="v2-section-heading"><p className="v2-kicker">Free compute / Requests open</p><h2 id="access-title">Tell us what you want to try.</h2></div><div className="v2-split"><div><p>The HITL AI Compute Grant Application is a request for access to hardware for open research and projects. Submitting it does not provision compute or guarantee an allocation.</p><h3 style={{marginTop:"1.5rem"}}>Have these details ready.</h3><ul><li>Your project, what you want to learn or build, and how it benefits the community.</li><li>The resources you expect to need: GPU, memory, number of nodes, or estimated time.</li><li>How you will share your open work, progress, and results publicly and tag HITL, as required by the form.</li></ul><a className="v2-button v2-button--primary" href={siteConfig.labRequestUrl} target="_blank" rel="noreferrer">Open the compute grant application ↗</a></div><div><h3>What to expect.</h3><p>Requests are reviewed against available capacity. Access and resource allocations are arranged after review; there is no immediate booking through the form.</p><p className="v2-form-expectations">The form asks applicants to conduct open work that contributes back, share progress and results publicly, and tag HITL. Read its full agreements before applying.</p><p className="v2-note">Community participation is separate. You don’t need to apply for compute to join a conversation or share your work.</p><a className="v2-link" href="/v2/community#connect">Connect with HITL →</a></div></div></div></section>

    <section className="v2-dark" id="support" aria-labelledby="support-title"><div className="v2-wrap v2-section"><p className="v2-kicker">Support the Lab</p><h2 id="support-title">Have hardware or hosting space to offer?</h2><p className="v2-lede"><a className="v2-link" href="/v2/why#founder">Shannon Duncan</a> built and funded the Lab for his own open source work and to share capacity with HITL. These are practical ways to discuss supporting that work.</p><div className="v2-support-options"><article><h3>Space to host it.</h3><p>The build uses a 12U, 10-inch mini rack with external benches. Share your location, available space, and any operating or access constraints.</p></article><article><h3>Power & connectivity.</h3><p>Power and bandwidth help keep shared hardware useful. The operating model gives a starting point for a hosting conversation.</p><a className="v2-link" href="#costs">See the power estimates ↓</a></article><article><h3>Hardware that fits.</h3><p>Tell us the model, condition, and location of equipment you can offer. We can discuss it against the existing inventory and what the Lab needs.</p></article></div><div className="v2-support-contact"><div><h3>Start with a conversation.</h3><p className="v2-note" style={{marginTop:'.75rem'}}>Tell Shannon what you can offer and any constraints. Equipment, delivery, hosting, and operating arrangements can be discussed before anything changes hands.</p></div><FounderLinks /></div></div></section>

    <section className="v2-wrap v2-section v2-costs" id="costs" aria-labelledby="costs-title"><div className="v2-section-heading"><p className="v2-kicker">Stewardship / Planning estimates</p><h2 id="costs-title">What it takes to run.</h2></div><div className="v2-cost-layout"><div><p className="v2-kicker">Estimated replacement cost</p><p className="v2-cost-total">$29,749</p><p className="v2-note">September 11–12, 2026 pricing snapshot. Replacement estimate, not the amount spent or a donation valuation.</p><dl className="lab-cost-breakdown"><div><dt>Compute hardware & add-ons</dt><dd>$28,244</dd></div><div><dt>Rack, network, control & power</dt><dd>$1,505</dd></div></dl><a className="v2-link" href="/lab/build-list.md" download>Itemized costs & price references ↓</a><h3>Estimated wall power</h3><div className="lab-table-wrap"><table className="lab-power-table"><caption>Watts by workload scenario</caption><thead><tr><th scope="col">Setup</th><th scope="col">Idle</th><th scope="col">Working</th><th scope="col">Heavy</th></tr></thead><tbody><tr><th scope="row">Core cluster</th><td>229.8 W</td><td>406.5 W</td><td>907 W</td></tr><tr><th scope="row">Whole lab</th><td>339.3 W</td><td>693 W</td><td>1,413 W</td></tr></tbody></table></div><p className="v2-note">Planning estimates, not meter readings. Whole lab adds the V100 dock, FPGA and small-device benches, and a projected populated Agent Blade. Spare GPUs are not added together. The 750 VA UPS serves essential loads and is not sized for the whole lab at heavy load.</p><a className="v2-link" href="/lab/power-notes.md" download>Power assumptions & references ↓</a></div><LabPowerEstimate /></div></section>

    <section className="v2-connection" id="journey" aria-labelledby="journey-title"><div className="v2-wrap v2-section"><div className="v2-section-heading"><p className="v2-kicker">September 6–8, 2026 / The build journey</p><h2 id="journey-title">Built together.<br />Learned along the way.</h2></div><div className="v2-split"><LabPhoto name="building-together" alt="Shannon and his daughter beside the mini cluster they built together." caption="Shannon and his daughter with the assembled rack." /><div className="v2-prose"><p>This mini cluster was a project Shannon built with his daughter.</p><p>The first evening meant laying out parts, assembling the rack, and figuring out how everything would fit. His daughter picked the colorful zip ties for the exhaust fan and suggested putting a mini PC on the back to make room.</p><p>After coffee and donuts, they returned to network cabling, cooling, and conversations about AC, DC, and why current matters. By September 8, the first two Sparks and a mini PC were online, brought up one system at a time using a Mac and HDMI capture as the console.</p><div className="v2-actions"><a className="v2-button" href={siteConfig.buildThreadUrl} target="_blank" rel="noreferrer">Follow the build thread ↗</a><a className="v2-link" href="https://x.com/iamMrDuncan/status/2096739567537652149" target="_blank" rel="noreferrer">Read on X ↗</a></div></div></div><div className="v2-journey-gallery"><LabPhoto name="parts-on-the-bench" alt="Cluster parts, tools, and hardware laid out before assembly." caption="September 6: laying out the parts." /><LabPhoto name="rack-assembly" alt="The empty TecMOJO rack frame being assembled on the floor." caption="September 6: assembling the rack." /><LabPhoto name="sparks-in-the-rack" alt="Shannon’s daughter beside the rack with three DGX Sparks installed." caption="September 7: three Sparks mounted." /><LabPhoto name="gpu-test-bench" alt="The external GPU bench with a graphics card, power supply, cables, and cooling fans." caption="The swappable GPU bench." /></div></div></section>
  </>;
}
