export const hardware = [
  ["AI compute", "3 × NVIDIA DGX Spark", "128 GB unified memory and 4 TB NVMe each. 384 GB of memory across three separate machines for inference and training experiments. The build thread describes a two-Spark pair plus one standalone Spark."],
  ["General compute", "MS-A2, N150, and K15", "MS-A2: Ryzen 9 9955HX, 96 GB RAM, 6 TB SSD. N150 controller: 16 GB, 500 GB SSD + 5 TB USB HDD. K15: Core Ultra 5 125U, 32 GB, 512 GB SSD + 4 TB NVMe; also hosts the GPU bench."],
  ["GPU bench", "19 cards on hand. One dock.", "8 P100s, 2 V100s, 2 BC-160s, 2 Radeon VIIs, 1 P4, 2 RTX 5070s, 1 RTX 4070 SUPER, and 1 Intel Arc Pro B70. This count includes spares and cards whose installation is unconfirmed. The documented DEG2 dock connects to the K15 and runs one GPU at a time."],
  ["Storage", "QNAP TS-464", "4 × 8 TB WD Red Plus HDDs in RAID5: 32 TB raw, about 24 TB after parity and before overhead. One 4 TB WD Blue NVMe drive provides the Qtier SSD tier."],
  ["Small-device experiments", "FPGA, edge AI, and ESP32", "Custom i5 host and TANG Primer 20K, Stratix V, Kintex-7, and XCKU3P FPGA platforms. Orange Pi 6, Luckfox Pico Mini A, Grove Vision AI Module V2, AX630C LLM module, M5Stack ESP32-S3 devices, and the experimental Agent Blade."],
  ["Electronics bench", "Power, soldering, and prototyping", "WEP 605D-III 60 V / 5 A DC supply, soldering setup, and embedded boards for hardware experiments. These bench tools are in the inventory; their operating draw depends on the work underway."],
  ["Rack and control", "12U TecMOJO / 10-inch rack", "NETGEAR GS108E switch, patch panel, eight-port KVM, Sipeed NanoKVM, rack displays, fans, power meter, and CyberPower 750 VA and PR2200LCDSL UPS units. The new UPS installation and protected loads have not been confirmed."],
] as const;
